{% set version = "0.8.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pdp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pdp_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pdp/pdp_{{ version }}.tar.gz
  sha256: 4c49f379bf25a1117cfba5202fc85d035795b346e377a375c00dc238743392c6

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-foreach
    - r-ggplot2 >=3.0.0
    - r-lattice
    - r-rlang >=0.3.0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-foreach
    - r-ggplot2 >=3.0.0
    - r-lattice
    - r-rlang >=0.3.0

test:
  commands:
    - $R -e "library('pdp')"           # [not win]
    - "\"%R%\" -e \"library('pdp')\""  # [win]

about:
  home: https://bgreenwell.github.io/pdp/index.html, https://github.com/bgreenwell/pdp
  license: GPL-2.0-or-later
  summary: A general framework for constructing partial dependence (i.e.,  marginal effect) plots from various types machine learning models in R.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - fhoehle

# Package: pdp
# Type: Package
# Title: Partial Dependence Plots
# Version: 0.7.0
# Authors@R: person("Brandon", "Greenwell", email = "greenwell.brandon@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-8120-0084"))
# Description: A general framework for constructing partial dependence (i.e.,  marginal effect) plots from various types machine learning models in R.
# License: GPL (>= 2)
# URL: https://bgreenwell.github.io/pdp/index.html, https://github.com/bgreenwell/pdp
# BugReports: https://github.com/bgreenwell/pdp/issues
# Depends: R (>= 3.2.5)
# Suggests: adabag, AmesHousing, C50, caret, Cubist, doParallel, dplyr, e1071, earth, gbm, ipred, keras, kernlab, MASS, mda, nnet, party, partykit, progress, randomForest, ranger, rpart, testthat, xgboost (>= 0.6-0), knitr, rmarkdown, vip
# Imports: ggplot2 (>= 0.9.0), grDevices, gridExtra, lattice, magrittr, methods, mgcv, plyr, stats, viridis, utils
# LazyData: TRUE
# RoxygenNote: 6.1.0
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2018-08-27 17:20:57 UTC; b780620
# Author: Brandon Greenwell [aut, cre] (<https://orcid.org/0000-0002-8120-0084>)
# Maintainer: Brandon Greenwell <greenwell.brandon@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-08-27 17:50:03 UTC
